name: 🔄 Refresh dependencies

on:
  schedule:
    - cron: "0 5 * * MON"
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: python -m pip install --upgrade pip setuptools wheel pip-tools

      - name: Compile fresh requirements
        run: pip-compile requirements.in --output-file=requirements.txt

      - name: Check for changes
        run: git --no-pager diff --exit-code requirements.txt

        #Installer et tester les dépendances
      - name: Test installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip check

      #   Ouvrir une PR automatique
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update dependencies via pip-compile"
          branch: refresh-deps
          title: "🔄 Update dependencies"
          body: "Mise à jour automatique de requirements.txt"
